const researchTopics = [
    {
        id: 29,
        title: "Dominando a Nuvem (25 Casos de Uso)",
        category: "INFRA",
        resumo_status_curto: "Estudo de padrões essenciais de Cloud Computing (IaaS, Serverless, etc.) para configurar a infraestrutura segura e eficiente que hospeda sistemas de risco.",
        resumo_status: "Pesquisa em andamento: Entender 25 padrões de solução (VPC, Serveless, etc.) e como configurar redes privadas (VNet) para isolar dados financeiros em ambientes de Nuvem (Tema 29).",
        link: "https://medium.com/@devopsdiariesinfo/mastering-cloud-is-easy-read-these-25-use-cases-4ed6e95f9ff0",
    },
    {
        id: 32,
        title: "Medallion Architecture: Indo Além da superficie",
        category: "DATA ENG",
        resumo_status_curto: "Análise profunda da arquitetura Medallion (Bronze/Silver/Gold) e otimizações do Spark (AQE, Shuffling) para garantir a alta performance e qualidade dos dados de risco.",
        resumo_status: "Concluído o estudo sobre Bronze, Silver e Gold. Próximo passo: Implementar e otimizar pipelines (usando Spark e Delta Lake) para garantir que os dados de Fraude (Silver/Gold) sejam estruturados e performáticos. Foco em Planos de Execução Spark (AQE).",
        link: "https://medium.com/towards-data-engineering/medallion-architecture-is-not-enough-4d9cfde85e8c",
    },
    {
        id: 22,
        title: "Nova Funcionalidade em Apache Spark",
        category: "DATA ENG",
        resumo_status_curto: "Pesquisa de novos recursos do Apache Spark e Delta Lake focados em processamento massivo e governança de dados, visando a melhoria contínua dos pipelines de risco.",
        resumo_status: "Foco em otimização de queries e Particionamento para features de risco complexas. Pesquisar sobre o impacto do Photon e as novas features de governança no Delta Lake.",
        link: "https://blog.dataengineerthings.org/is-this-feature-a-revolution-in-spark-29636b690ea7",
    },
    {
        id: 9,
        title: "Masterizando Kubernetes",
        category: "MLOPS",
        resumo_status_curto: "Estudo da orquestração de contêineres e conceitos de Deployment e Services, essenciais para o deployment seguro e a escalabilidade contínua dos modelos de MLOps.",
        resumo_status: "Pesquisa em andamento: Estudo de Deployment, Services e como K8s escala modelos de fraude (MLflow). Objetivo: Entender a orquestração de contêineres que hospeda a API de risco.",
        link: "https://medium.com/@devopsdiariesinfo/mastering-one-question-at-a-time-in-kubernetes-0e3327585db4",
    },
    {
        id: 25,
        title: "Detecção de Fraudes (Superv./Unsuperv.)",
        category: "RISCO",
        resumo_status_curto: "Modelagem de risco híbrida (Supervisionada e Não Supervisionada) em transações, focada na detecção de anomalias (outliers) para aumentar o Recall em novos padrões de fraude.",
        resumo_status: "Próximo passo: Implementar um modelo Unsupervised (Isolation Forest) e comparar performance com Logistic Regression em um dataset de transações para aumentar o Recall na detecção de anomalias.",
        link: "https://yashvaantlakham73.medium.com/implementing-supervised-and-unsupervised-fraud-approaches-to-fraud-detection-160031ab5592",
    },
    {
        id: 28,
        title: "IA Responsável (RAI) e XAI em Crédito",
        category: "COMPLIANCE",
        resumo_status_curto: "Implementação de Explainable AI (XAI) usando SHAP/LIME para auditar e garantir que as decisões de crédito sejam justas, transparentes e em conformidade com as regulamentações.",
        resumo_status: "Concluído o estudo de SHAP e LIME. Próximo passo: Integrar métricas de Fairness (Aequitas) no pipeline de crédito para garantir que a decisão do modelo não seja enviesada, em conformidade com regulamentações.",
        link: "https://medium.com/@databricksfinserv/responsible-ai-in-credit-decisioning-turning-black-boxes-into-glass-boxes-77e8ea5aded2",
    },
    {
        id: 24,
        title: "Construção de Função de Segurança de Dados",
        category: "COMPLIANCE",
        resumo_status_curto: "Criação de um *pipeline* de segurança (AI SecOps) usando Vector Databases (Pinecone) para moderação e detecção de PII e tópicos sensíveis em inputs de LLMs.",
        resumo_status: "Pesquisa em andamento: Implementação de Pseudonimização e Anonimização de dados de clientes, e uso de Vector Databases para checagem semântica de inputs de risco (AI SecOps).",
        link: "https://blog.devgenius.io/building-a-data-security-function-f3e398f88327",
    },
    {
        id: 10,
        title: "MLflow Model Serving e Artifact Mgmt.",
        category: "MLOPS",
        resumo_status_curto: "Gestão do ciclo de vida do modelo (MLflow): Empacotamento, versionamento e tracking de modelos complexos e seus artefatos para deployment seguro e reprodutível.",
        resumo_status: "Próximo passo: Configurar tracking e versionamento do modelo de fraude (ID 25) e garantir o deployment seguro no K8s (ID 9) usando MLflow para gestão de artefatos.",
        link: "https://medium.com/@AI-on-Databricks/a-practical-guide-to-logging-packaging-and-accessing-artifacts-in-mlflow-model-serving-to-deploy-80a1c26974d8",
    },
    {
        id: 4,
        title: "FastAPI APIs e Segurança (Autenticação)",
        category: "MLOPS",
        resumo_status_curto: "Desenvolvimento de APIs de alta performance (FastAPI) com autenticação OAuth2/JWT, cruciais para a comunicação segura e escalável de modelos de risco em produção.",
        resumo_status: "Pesquisa em andamento: Configurando OAuth2 e JWT para proteger o endpoint de scoring de risco (Fraude/Crédito). Essencial para a segurança da comunicação com o modelo (ID 10).",
        link: "https://medium.com/@tam.tamanna18/from-fastapi-apis-to-secure-mcp-tools-authentication-essentials-5d2053f33ace",
    },
    {
        id: 6,
        title: "LangExtract (Extração c/ IA Generativa)",
        category: "DATA SCIENCE",
        resumo_status_curto: "Utilização de Large Language Models (LLMs) para a extração estruturada de dados não estruturados de relatórios e documentos, gerando features de risco valiosas.",
        resumo_status: "Pesquisa em andamento: Usando modelos LLM para extrair informações de risco de cláusulas contratuais ou relatórios financeiros não estruturados.",
        link: "https://generativeai.pub/introducing-langextract-e8a85389e396",
    },
    {
        id: 23,
        title: "IBM Granite Docling",
        category: "DATA SCIENCE",
        resumo_status_curto: "Estudo sobre parsers multimodais (VLM) especializados em extrair tabelas e estruturas complexas de documentos, complementando a extração de LLMs.",
        resumo_status: "Estudo como ferramenta complementar ao LangExtract para otimização de documentos padronizados, com foco na extração precisa de tabelas e fórmulas financeiras.",
        link: "https://medium.com/data-science-in-your-pocket/ibm-granite-docling-the-best-ai-document-parser-0f4e3de079cb",
    },
    {
        id: 7,
        title: "HTML Estático para Live Dashboard",
        category: "VISUALIZAÇÃO",
        resumo_status_curto: "Aplicação de técnicas de Frontend (JS/CSS) para criar um dashboard visual dinâmico, ideal para apresentar métricas de MLOps (ID 10) e resultados de XAI (ID 28).",
        resumo_status: "Este projeto é o produto deste tópico! Utilizando JS para criar uma visualização dinâmica e simples dos dados, como métricas de performance (ID 10) e resultados de XAI (ID 28).",
        link: "https://medium.com/@tam.tamanna18/transforming-a-static-html-page-into-a-live-dashboard-dbe6511ee4b9",
    }
];